### ISSUE TITLE
mypy failures after upgrade to 1.15.0

### ISSUE THREAD

**Issue by nik-localstack** [getmoto/moto#8566]
There are many error in master branch after upgrading to latest mypy 

```
% make lint
Running ruff...
ruff check moto tests
All checks passed!
ruff format --check moto tests
2289 files already formatted
Running pylint...
pylint -j 0 moto tests

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

Running MyPy...
mypy --install-types --non-interactive
moto/core/responses.py:306:9: error: Type of decorated function contains type "Any" ("_Wrapped[[ResponseShape, Any, str, Any], tuple[int, dict[str, Any], str | bytes], [Any, str, Any], tuple[int, dict[str, Any], str | bytes]]")  [misc]
moto/kinesis/models.py:812:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/s3/models.py:200:5: error: Function is untyped after decorator transformation  [misc]
moto/logs/models.py:806:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/ssoadmin/models.py:250:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/ssoadmin/models.py:271:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/medialive/models.py:177:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/medialive/models.py:271:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/ivs/models.py:66:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/identitystore/models.py:263:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/identitystore/models.py:275:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/identitystore/models.py:288:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/bedrockagent/models.py:228:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/bedrockagent/models.py:277:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/bedrock/models.py:305:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/bedrock/models.py:422:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/organizations/models.py:541:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/organizations/models.py:633:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/appmesh/models.py:253:5: error: Function is missing a return type annotation  [no-untyped-def]
moto/appmesh/models.py:253:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/appmesh/models.py:287:5: error: Function is missing a return type annotation  [no-untyped-def]
moto/appmesh/models.py:287:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/appmesh/models.py:379:5: error: Function is missing a return type annotation  [no-untyped-def]
moto/appmesh/models.py:379:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/appmesh/models.py:511:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/appmesh/models.py:606:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/wafv2/models.py:517:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/wafv2/models.py:525:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[Any], str | None]]")  [misc]
moto/iot/models.py:2307:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/iot/models.py:2399:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/iot/models.py:2646:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
moto/route53resolver/models.py:756:5: error: Type of decorated function contains type "Any" ("Callable[P2, tuple[list[dict[str, Any]], str | None]]")  [misc]
Found 32 errors in 15 files (checked 1025 source files)
make: *** [lint] Error 1
```

Also visible here https://github.com/getmoto/moto/actions/runs/13153249729/job/36704589306?pr=8563

**Comment by bblommers** [comment]
Thanks for letting us know @nik-localstack! I've raised a PR to fix all these
