### PR TITLE
S3: Improve bucket policy enforcement

### LINKED ISSUE #5820: Error is not displaying when we add "deny policy" to S3 buckets.
@bblommers 

Steps:

1. Create a new S3 bucket.
2. Add the policy with the effect set to deny.
3. Upload a file and observe.

Actual: No error is displayed after uploading the file.

Expected : When our policy effect is "Deny," an access denied error message should be displayed. 

Code : 
     bucket_policy = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Deny",
                "Principal": "*",
                "Action": "s3:*",
                "Resource": ["arn:aws:s3:::testbucket","arn:aws:s3:::testbucket/*"],
                "Condition": {
                    "ArnNotLikeIfExists": {
                        "aws:PrincipalArn": [
                            "arn:aws:iam::(userid):role/lambda-execution-role"
                        ]
                    }
                }
            }
        ]
    }

    s3_client = boto3.client('s3')
    s3_client.create_bucket(Bucket='testbucket')

    file_path = 'C://Users//PycharmProjects//datbase//inputs//'
    object_name = 'expectedfile.csv'
    s3_client.put_bucket_policy(Bucket='testbucket', Policy=json.dumps(bucket_policy))
    result = s3_client.get_bucket_policy_status(Bucket='testbucket')
    path_of_file = os.path.join(file_path, object_name)
    res = s3_client.upload_file(path_of_file, 'testbucket', 'hello.csv')
    reading_content = s3_client.get_object(Bucket='testbucket', Key='hello.csv')
    print(reading_content["Body"].read())

Please do let me know where i am doing wrong.

Help me

https://www.geeksforgeeks.org/create-bucket-policy-in-aws-s3-bucket-with-python/

i need to restrict bucket policy in s3 bucket.

### PR DESCRIPTION
**Pull request by bblommers**
Fixes #5820

### CODE REVIEW

**Comment by agroszer** [comment]
Latest boto3 s3.Bucket does not have `get_permission`? Or do I miss there something?

```
  File "/work/shoobx/shoobx.mocks3/src/shoobx/mocks3/tests/test_s3_boto3.py", line 790, in test_unicode_value
    body = self.retrieve_key("some_key")
  File "/work/shoobx/shoobx.mocks3/src/shoobx/mocks3/tests/test_s3_boto3.py", line 84, in retrieve_key
    return self.s3.get_object(Bucket=bucket, Key=name)["Body"]
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/retryhandler.py", line 307, in _should_retry
    return self._checker(
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/endpoint.py", line 278, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/moto/core/botocore_stubber.py", line 61, in __call__
    status, headers, body = response_callback(
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/moto/utilities/aws_headers.py", line 64, in _wrapper
    response = f(*args, **kwargs)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/moto/s3/responses.py", line 1122, in key_response
    response = self._key_response(request, full_url, self.headers)
  File "/work/shoobx/shoobx.mocks3/ve/lib/python3.10/site-packages/moto/s3/responses.py", line 1176, in _key_response
    bucket_permissions = bucket.get_permission(action, resource)
AttributeError: 'Bucket' object has no attribute 'get_permission'
```

Our code works fine with moto 4.1.1, breaks with 4.1.2

**Comment by bblommers** [comment]
The class-name in Moto is `FakeBucket`, so I don't understand where the error message comes from (`Bucket` object has no attribute..). 
And the `get_permission`-method is still present in FakeBucket:

https://github.com/getmoto/moto/blob/db9654a059afccf7b2e104a705729e92f2a48498/moto/s3/models.py#L937

Please open a new issue with an MRE @agroszer if this still persists, that will make it easier to track.

**Comment by agroszer** [comment]
nevermind... missed that shoobx.mocks3 uses it's own `Bucket`
