### PR TITLE
Properly handle CopyObject with content length 0 in moto_server after checksum workaround

### LINKED ISSUE #8592: Submitting a S3 CopyObject to replace user metadata with Content-Length 0 causes Error 500 after the checksum workaround
Example request:
```
[DEBUG] 2025-02-13 20:48:40.015 CURL [140340847924992] (HeaderOut) PUT /s3testbucket/dst/testfile HTTP/1.1
Host: 127.0.0.1:12509
Accept: */*
amz-sdk-invocation-id: 008050B0-3919-4A52-AA41-5E93710D4049
amz-sdk-request: ttl=20250213T205140Z; attempt=4
authorization: ...
content-encoding: aws-chunked
content-length: 0
content-type: binary/octet-stream
user-agent: aws-sdk-cpp/1.11.500 md/internal ua/2.1 api/S3 os/Linux#5.10.233-204.894.x86_64 lang/c++#C++11 md/aws-crt#0.30.1 md/arch#x86_64 md/GCC#7.3.1 m/Z,b
x-amz-api-version: 2006-03-01
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-copy-source: s3testbucket/dst/testfile
x-amz-copy-source-if-match: "620f0b67a91f7f74151bc5be745b7110"
x-amz-date: 20250213T204840Z
x-amz-meta-last-modified: 1739479675000
x-amz-meta-usermetakey: usermetaval
x-amz-metadata-directive: REPLACE
x-amz-security-token: ...
```

Example 500 stack:
```
Error on request:
Traceback (most recent call last):
  File "/test-runtime/lib/python3.9/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/test-runtime/lib/python3.9/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "/test-runtime/lib/python3.9/site-packages/moto/moto_server/werkzeug_app.py", line 264, in __call__
    return backend_app(environ, start_response)
  File "/test-runtime/lib/python3.9/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/test-runtime/lib/python3.9/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/test-runtime/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/test-runtime/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/test-runtime/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/test-runtime/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/test-runtime/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/test-runtime/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/test-runtime/lib/python3.9/site-packages/moto/core/utils.py", line 112, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/test-runtime/lib/python3.9/site-packages/moto/core/responses.py", line 307, in _inner
    response = getattr(cls(), to_call.__name__)(request, full_url, headers)
  File "/test-runtime/lib/python3.9/site-packages/moto/s3/responses.py", line 1377, in key_response
    self.setup_class(request, full_url, headers)
  File "/test-runtime/lib/python3.9/site-packages/moto/s3/responses.py", line 191, in setup_class
    self.body = request.input_stream.getvalue()
AttributeError: '_io.BufferedReader' object has no attribute 'getvalue'
```

Code in question:
https://github.com/getmoto/moto/blob/c2a0d9c1af441ab1f72d741d1c0711e4924a5422/moto/s3/responses.py#L191

I'm not sure where the BufferedReader comes from; it does not appear to be from moto.

### PR DESCRIPTION
**Pull request by jeking3**
Caused by #8495
This fixes #8592

It was broken with the checksum workaround. The workaround relied on something dangerous called `input_stream` defined in werkzeug on the request, and it is not always an `io.BytesIO`; sometimes it is a `BufferedReader`, sometimes it is a `bytes`.

https://github.com/pallets/werkzeug/blob/7868bef5d978093a8baa0784464ebe5d775ae92a/src/werkzeug/wrappers/request.py#L355-L364
```
    input_stream = environ_property[t.IO[bytes]](
        "wsgi.input",
        doc="""The raw WSGI input stream, without any safety checks.

        This is dangerous to use. It does not guard against infinite streams or reading
        past :attr:`content_length` or :attr:`max_content_length`.

        Use :attr:`stream` instead.
        """,
    )
```

I could not reproduce the behavior with a moto unit test; but it was failing when using the AWS SDK for C++ against a moto_server. The unit test framework must not be standing up a full moto_server or the C++ SDK is doing something different than boto3.

### CODE REVIEW

**Comment by bpandola** [comment]
The `TestRecorder.test_s3_upload_data` failure you're getting on this changeset is the same failure that made me add that hacky bit of code in the first place... 🙃  I didn't feel like digging into it at the time, but there's clearly some path taken (or not taken) when we replay the request via the moto recording API and, from the issue you opened, use the AWS SDK for C++.

I think this one might be a bit tricky to nail down, but let us know if you're willing to keep working on it.  Ultimately, we need a higher level abstraction to "normalize" all incoming requests to moto, regardless of source (e.g. boto3, recording API, other language SDKs, etc.), instead of doing these hacky one-off parsings at the individual service  level (s3 in this case); but that would be a much more significant scope/effort.

**Comment by jeking3** [comment]
Check out https://github.com/getmoto/moto/pull/8593/files which was my first attempt.  I didn't have coverage but it fixes my issue _and_ passed the tests, however there was no coverage for the alternate code path and I could not reproduce it with a unit test.

**Comment by jeking3** [comment]
The build failure is environmental - not related to the code.

**Review by bpandola — APPROVED** [review]
Thanks for figuring this out, @jeking3!

**Comment by bblommers** [comment]
FYI @jeking3 and @bpandola - I've added some basic S3 tests using the C++ SDK:

https://github.com/getmoto/moto/pull/8613

It does not cover this exact scenario yet, I just wanted to provide a rough draft. Suggestions/improvements are very welcome!
