### ISSUE TITLE
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' with moto 4.1.7 and werkzeug 2.2.3

### ISSUE THREAD

**Issue by radifalco** [getmoto/moto#6237]
When using moto server I am getting the following stack trace. I think moto is incompatible with any werkzeug greater than 2.0.3

Here's the full stack trace. 
```
  "When using MotoServer, ensure that you install moto[server] to have all dependencies!\n"
Traceback (most recent call last):
  File "/usr/local/bin/moto_server", line 5, in <module>
    from moto.server import main
  File "/usr/local/lib/python3.7/site-packages/moto/server.py", line 9, in <module>
    from moto.moto_server.werkzeug_app import (
  File "/usr/local/lib/python3.7/site-packages/moto/moto_server/werkzeug_app.py", line 8, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 32, in <module>
    from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/usr/local/lib/python3.7/site-packages/werkzeug/wrappers/__init__.py)

```

**Comment by bblommers** [comment]
Which versions of `moto` and `werkzeug` do you have installed @radifalco?

**Comment by bblommers** [comment]
I deleted my earlier comment asking about the versions - I somehow completely missed the fact you mentioned the versions in the title.

It looks like you have an older version of `flask` installed. Only version `1.x` import BaseResponse directly:
https://github.com/pallets/flask/blob/1.1.x/src/flask/app.py#L32

From `flask 2.x`, it imports `Response as BaseResponse`:
https://github.com/pallets/flask/blob/2.0.x/src/flask/app.py#L26
https://github.com/pallets/flask/blob/2.1.x/src/flask/app.py#L25
https://github.com/pallets/flask/blob/2.2.x/src/flask/app.py#L32

Flask and Werkzeug typically always need to have the same minor version to be compatible (i.e. `flask==2.2.x` with `werkzeug==2.2.3`)

**Comment by andrewsw** [comment]
@radifalco confirmed that flask == 2.2.3 and werkzeug == 2.2.3 works with moto == 4.1.8.dev31. You can crib off my branch if you want.

**Comment by bblommers** [comment]
I'm going to assume this is fixed - let us know if you run into any other issues.
